name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - uses: actions/setup-go@v2
        with:
          go-version: '1.13'
        env:
          GOPATH: ${{ github.workspace }}

      - uses: actions/cache@v1
        with:
          path: ${{ github.workspace }}/provider/vendor/
          key: go-${{ hashFiles('**/go.sum') }}

      - name: Prepare environment
        run: |
          # Install pyenv
          curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
          exec $SHELL

          git clone https://github.com/pulumi/scripts ${GOPATH}/src/github.com/pulumi/scripts
          source ${GOPATH}/src/github.com/pulumi/scripts/ci/prepare-environment.sh
          source ${PULUMI_SCRIPTS}/ci/install-common-toolchain.sh
          curl -L https://get.pulumi.com/ | bash
          export PATH=$HOME/.pulumi/bin:$PATH
          ${PULUMI_SCRIPTS}/ci/ensure-dependencies
        shell: bash -l {0}
        env:
          GOPATH: ${{ github.workspace }}

      - name: Build
        run: make github_push_ci
        env:
          GOPATH: ${{ github.workspace }}

      - name: Publish SDK and plugin to S3
        run: make github_deploy_ci
        env:
          GOPATH: ${{ github.workspace }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}