name: CI
on: [ push ]

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Discover Go cache paths
        id: go-cache-paths
        run: |
          echo "::set-output name=go-mod-cache::$(go env GOMODCACHE)"
          echo "::set-output name=go-build-cache::$(go env GOCACHE)"

      - uses: actions/cache@v2
        with:
          path: ${{ steps.go-cache-paths.outputs.go-mod-cache }}
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}

      - uses: actions/cache@v2
        with:
          path: ${{ steps.go-cache-paths.outputs.go-build-cache }}
          key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}

      - name: Build
        run: make github_push_ci

      - name: Publish SDK and plugin to S3
        run: |
          if [ "$GITHUB_REF" != "refs/heads/master" ]; then export TARGET_DIRECTORY='/feature' ; else export TARGET_DIRECTORY='/' ; fi
          make github_deploy_ci
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-central-1
          TARGET_S3_BUCKET: moneymeets-pulumi-provider
